-- Snowflake Data Warehouse Assignment
-- Student: Sania Sharma

-- 1. SETUP CORE INFRASTRUCTURE

CREATE OR REPLACE WAREHOUSE PROD_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 180
AUTO_RESUME = TRUE;

USE WAREHOUSE PROD_WH;

CREATE OR REPLACE DATABASE STORE_DB;
USE DATABASE STORE_DB;

CREATE OR REPLACE SCHEMA INVENTORY_SCHEMA;
USE SCHEMA INVENTORY_SCHEMA;


-- 2. CREATE TABLE AND STAGE

CREATE OR REPLACE TABLE INVENTORY (
    SKU_ID INT,
    PRODUCT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    UNIT_PRICE NUMBER(8,2),
    STOCK_COUNT INT
);

CREATE OR REPLACE STAGE PRODUCT_STAGE;


-- 3. INVENTORY DATA OPERATIONS

INSERT INTO INVENTORY
    (SKU_ID, PRODUCT_NAME, CATEGORY, UNIT_PRICE, STOCK_COUNT)
VALUES
    (5001, 'Mechanical Keyboard', 'Electronics', 120.00, 45),
    (5002, 'Ergonomic Chair', 'Furniture', 350.00, 12),
    (5003, '4K Monitor', 'Electronics', 400.00, 20);

SELECT * FROM INVENTORY;

UPDATE INVENTORY
SET UNIT_PRICE = 110.00
WHERE SKU_ID = 5001;

DELETE FROM INVENTORY
WHERE SKU_ID = 5003;

SELECT * FROM INVENTORY;


-- 4. CREATE ORDERS TABLE

CREATE OR REPLACE TABLE ORDERS_LOG (
    ORDER_ID INT,
    ORDER_STATUS VARCHAR(30)
);

INSERT INTO ORDERS_LOG
    (ORDER_ID, ORDER_STATUS)
VALUES
    (801, 'Processing'),
    (802, 'Shipped'),
    (803, 'Pending');

SELECT * FROM ORDERS_LOG;

UPDATE ORDERS_LOG
SET ORDER_STATUS = 'Cancelled'
WHERE ORDER_ID = 801;

DELETE FROM ORDERS_LOG
WHERE ORDER_ID = 803;

SELECT * FROM ORDERS_LOG;


-- 5. TIME TRAVEL DEMONSTRATION

SELECT CURRENT_TIMESTAMP();

SELECT *
FROM ORDERS_LOG
AT(OFFSET => -60*3);


-- 6. TIME TRAVEL ORDERS TABLE

CREATE OR REPLACE TABLE TIME_TRAVEL_ORDERS (
    ORDER_ID INT,
    ORDER_STATUS VARCHAR(30)
);

INSERT INTO TIME_TRAVEL_ORDERS
    (ORDER_ID, ORDER_STATUS)
VALUES
    (901, 'Processing'),
    (902, 'Shipped'),
    (903, 'Pending');

SELECT * FROM TIME_TRAVEL_ORDERS;

UPDATE TIME_TRAVEL_ORDERS
SET ORDER_STATUS = 'Cancelled'
WHERE ORDER_ID = 901;

DELETE FROM TIME_TRAVEL_ORDERS
WHERE ORDER_ID = 903;

SELECT * FROM TIME_TRAVEL_ORDERS;


-- 7. VERIFY CREATED OBJECTS

SHOW TABLES IN SCHEMA STORE_DB.INVENTORY_SCHEMA;

SHOW STAGES IN SCHEMA STORE_DB.INVENTORY_SCHEMA;